name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Run All
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: fcimc
          auto-activate-base: false
          auto-update-conda: true
          environment-file: environment.yml
          python-version: 3.7
      - run: |
          conda info
          conda list
          pwd
          ls -la
          git status
          git remote -vv show
          ./runall || true # TEMPORARY !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      - name: Update
        env:
          FCIMC_TOKEN: ${{ secrets.FCIMC_TOKEN }}
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "Build Bot"
          git add fortran/calcs/*.png python/calcs/*.png
          git commit -m "Updated graphs" || true
          git push || true
