name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: fcimc
          auto-activate-base: false
          auto-update-conda: true
          environment-file: environment.yml
          python-version: 3.7
      - run: |
          PATH="${PWD}/docs:${PATH}" make -C docs html
